services:
  allures-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allures-backend
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app:/app/common
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - allures-network

networks:
  allures-network:
