
services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - allures-network

  allures-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allures-backend
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app:/app/common
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres-db
    networks:
      - allures-network

volumes:
  postgres_data:

networks:
  allures-network:

