

services:
  auth_service:
    image: denstep123/auth-service:latest
    container_name: auth_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.auth_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8003:8000"]
    networks: [allures-net]

  product_service:
    image: denstep123/product-service:latest
    container_name: product_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.product_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    depends_on: [review_service]
    networks: [allures-net]

  review_service:
    image: denstep123/review-service:latest
    container_name: review_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.review_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8002:8000"]
    networks: [allures-net]

  subscription_service:
    image: denstep123/subscription-service:latest
    container_name: subscription_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      # PROD: префикс /subscription задаёт gateway → в приложении включаем root_path
      SUBSCRIPTION_USE_ROOT_PATH: "1"
    command: uvicorn services.subscription_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8011:8000"]
    networks: [allures-net]

  admin_service:
    image: denstep123/admin-service:latest
    container_name: admin_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      ADMIN_USE_ROOT_PATH: "1"        # ← ВКЛЮЧАЕМ root_path=/admin
      # внутренняя ссылка на сервис подписок в докер-сети
      SUBSCRIPTION_SERVICE_URL: "http://subscription_service:8000"
    command: uvicorn services.admin_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8010:8000"]
    depends_on: [subscription_service]
    networks: [allures-net]

  profile_service:
    image: denstep123/profile-service:latest
    container_name: profile_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.profile_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8004:8000"]
    networks: [allures-net]

  payment_service:
    image: denstep123/payment-service:latest
    container_name: payment_service
    restart: unless-stopped
    env_file: [/home/adminden/.env]
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.payment_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8005:8000"]
    networks: [allures-net]

  # опционально позже:
  # sales_service:    → ports ["8001:8000"]
  # discount_service: → ports ["8006:8000"]
  # dashboard_service:→ ports ["8007:8000"]

networks:
  allures-net:
    external: true

