
services:
  review_service:
    build:
      context: ./services/review_service
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8002:8000"
    volumes:
      - ./services/review_service:/app
      - ./common:/app/common
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app:/app/common
      MAINDB_URL: ${MAINDB_URL}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  postgres-data:
