services:
  discount_service:
    build:
      context: ./services/discount_service
      dockerfile: Dockerfile
    container_name: discount-service
    ports:
      - "8006:8000"
    volumes:
      - ./services/discount_service:/app
      - ./common:/app/common
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app:/app/common
      MAINDB_URL: ${MAINDB_URL}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres-db
    restart: always
