

networks:
  allures-network:
    driver: bridge

services:
  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.auth_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8003:8000"
    networks:
      - allures-network

  product_service:
    build:
      context: .
      dockerfile: services/product_service/Dockerfile
    container_name: product_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.product_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - allures-network

  review_service:
    build:
      context: .
      dockerfile: services/review_service/Dockerfile
    container_name: review_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.review_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    networks:
      - allures-network

  subscription_service:
    build:
      context: .
      dockerfile: services/subscription_service/Dockerfile
    container_name: subscription_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services/subscription_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8011:8000"
    networks:
      - allures-network

  payment_service:
    build:
      context: .
      dockerfile: services/payment_service/Dockerfile
    container_name: payment_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.payment_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8005:8000"
    networks:
      - allures-network



