# docker-compose.yml (корень) — ДОБАВЬ сервис review_service
version: "3.9"

networks:
  backend-net:
    driver: bridge

services:
  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app
      TZ: "Europe/Kyiv"
    command: uvicorn services.auth_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8003:8000"
    networks:
      - backend-net

  product_service:
    build:
      context: .
      dockerfile: services/product_service/Dockerfile
    container_name: product_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app
      TZ: "Europe/Kyiv"
    command: uvicorn services.product_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - backend-net

  review_service:
    build:
      context: .
      dockerfile: services/review_service/Dockerfile
    container_name: review_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app
      TZ: "Europe/Kyiv"
    command: uvicorn services.review_service.main:app --host 0.0.0.0 --port 8000
    # Для прод прокси — порт можно убрать; для локалки оставь:
    ports:
      - "8002:8000"
    networks:
      - backend-net
