
services:
  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8003:8000"
    volumes:
      - ./services/auth_service:/app
      - ./common:/app/common
    working_dir: /app
    env_file:
      - ./services/auth_service/.env
    depends_on:
      - postgres-db
    environment:
      PYTHONPATH: /app:/app/common
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./services/auth_service/.env
    restart: always

volumes:
  postgres-data:
