
services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"  # Порт PostgreSQL
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Хранение данных PostgreSQL
    env_file:
      - .env
    restart: always

volumes:
  postgres-data:


