version: "3.9"

services:
  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.auth_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8003:8000"]
    networks: [allures-network]

  product_service:
    build:
      context: .
      dockerfile: services/product_service/Dockerfile
    container_name: product_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.product_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    networks: [allures-network]

  review_service:
    build:
      context: .
      dockerfile: services/review_service/Dockerfile
    container_name: review_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.review_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8002:8000"]
    networks: [allures-network]

  subscription_service:
    build:
      context: .
      dockerfile: services/subscription_service/Dockerfile
    container_name: subscription_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      # DEV режим: роуты под /subscription
      SUBSCRIPTION_USE_ROOT_PATH: "0"
    command: uvicorn services.subscription_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8011:8000"]
    networks: [allures-network]

  payment_service:
    build:
      context: .
      dockerfile: services/payment_service/Dockerfile
    container_name: payment_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.payment_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8005:8000"]
    networks: [allures-network]

  profile_service:
    build:
      context: .
      dockerfile: services/profile_service/Dockerfile
    container_name: profile_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.profile_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8004:8000"]
    networks: [allures-network]

  admin_service:
    build:
      context: .
      dockerfile: services/admin_service/Dockerfile
    container_name: admin_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      # важно: в DEV ходим на /subscription
      SUBSCRIPTION_SERVICE_URL: "http://subscription_service:8000/subscription"
    command: uvicorn services.admin_service.main:app --host 0.0.0.0 --port 8000
    ports: ["8010:8000"]
    depends_on:
      - subscription_service
    networks: [allures-network]

networks:
  allures-network:
    external: true

