

services:
  review_service:
    build:
      context: .
      dockerfile: services/review_service/Dockerfile
    container_name: review_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app
      TZ: "Europe/Kyiv"
    command: uvicorn services.review_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    networks: [review-net]

networks:
  backend-net:
    driver: bridge

