
services:
  payment_service:
    build:
      context: .
      dockerfile: services/payment_service/Dockerfile
    container_name: payment_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env         # общий .env на сервере
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.payment_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8005:8000"                 # внешний 8005 → внутр. 8000
    networks: [backend-net]

networks:
  backend-net:
    driver: bridge
