

services:
  admin_service:
    build:
      context: .
      dockerfile: services/admin_service/Dockerfile
    container_name: admin_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
    command: uvicorn services.admin_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8010:8000"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
