

services:
  admin_service:
    build:
      context: .
      dockerfile: services/admin_service/Dockerfile
    container_name: admin_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      # ВАЖНО: всегда с хвостом /subscription, чтобы роутер админки не ошибся с путём
      SUBSCRIPTION_SERVICE_URL: "http://subscription_service:8000/subscription"
    command: uvicorn services.admin_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8010:8000"
    depends_on:
      - subscription_service
    networks:
      - allures-network

networks:
  allures-network:
    external: true
