

services:
  subscription_service:
    build:
      context: .
      dockerfile: services/subscription_service/Dockerfile
    container_name: subscription_service
    restart: unless-stopped
    env_file:
      - /home/adminden/.env
    environment:
      PYTHONPATH: /app:/app/common
      TZ: "Europe/Kyiv"
      # PROD (за gateway): роутер без префикса, root_path включён
      # DEV (локально): поставь 0, тогда префикс /subscription добавится в include_router
      SUBSCRIPTION_USE_ROOT_PATH: "1"
    command: uvicorn services.subscription_service.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8011:8000"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
