name: Build and Push Services

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mode:
        description: 'Режим запуска (auto, full, custom)'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - full
          - custom
      custom_services:
        description: 'Сервисы через запятую (если режим = custom)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Определение списка сервисов
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MODE="${{ github.event.inputs.mode }}"
            echo "Режим запуска: $MODE"

            if [ "$MODE" = "full" ]; then
              echo "changed_dirs=admin_service auth_service dashboard_service discount_service payment_service product_service profile_service review_service sales_service subscription_service" >> $GITHUB_OUTPUT

            elif [ "$MODE" = "custom" ]; then
              echo "changed_dirs=${{ github.event.inputs.custom_services }}" >> $GITHUB_OUTPUT

            else
              if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
                diff=$(git diff --name-only HEAD~1 HEAD)
              else
                diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
              fi
              changed=$(echo "$diff" | grep '^services/' | cut -d/ -f2 | uniq | tr '\n' ' ')
              echo "changed_dirs=$changed" >> $GITHUB_OUTPUT
            fi
          else
            diff=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            changed=$(echo "$diff" | grep '^services/' | cut -d/ -f2 | uniq | tr '\n' ' ')
            echo "changed_dirs=$changed" >> $GITHUB_OUTPUT
          fi

      - name: Debug changed_dirs
        run: echo "Изменённые сервисы: ${{ steps.changes.outputs.changed_dirs }}"

      - name: Build and push services
        uses: docker/build-push-action@v4
        if: contains(steps.changes.outputs.changed_dirs, 'admin_service')
        with:
          context: ./services/admin_service
          file: ./services/admin_service/Dockerfile
          push: true
          tags: denstep123/admin-service:latest

      # Далее по аналогии остальные сервисы (auth_service, dashboard_service и т.д.)
      # Добавим как шаблонный пример один, остальные можешь копипастить и заменить имя
      - name: Build and push auth_service
        if: contains(steps.changes.outputs.changed_dirs, 'auth_service')
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth_service
          file: ./services/auth_service/Dockerfile
          push: true
          tags: denstep123/auth-service:latest

      - name: Trigger server webhook
        run: |
          curl -X POST "${{ secrets.SERVER_WEBHOOK_URL }}" \
          -H "X-GitHub-Secret: ${{ secrets.WEBHOOK_SECRET }}"
