name: Build, Scan and Push Monolith Image

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/

      - name: Build Docker image
        run: docker build -t denstep123/allures-alloll-monolit:latest .

      - name: Scan Docker image with Trivy (report)
        run: |
          trivy image \
          --severity HIGH,CRITICAL \
          -f table \
          -o trivy-report.txt \
          denstep123/allures-alloll-monolit:latest

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt


      - name: Push Docker image
        if: success() # пушим только если Trivy не нашёл критичных
        run: docker push denstep123/allures-alloll-monolit:latest
